### ISSUE TITLE
2014-05-08 Meetup Ideas?

### ISSUE THREAD

**Issue by metaskills** [757rb/organizing#11]
NOTE: I have deleted all the files in this project. We are going to use issues just like @NorfolkJS

We need a topic for next month. @metaskills will be out at DCRUG for this date.

**Comment by rmcastil** [comment]
I think @switchspan wanted to give a talk. Can you confirm @therubyrep?

**Comment by switchspan** [comment]
@metaskills & @rmcastil  -- I can give a talk on BigQuery if you would like. :)

**Comment by lynnaloo** [comment]
I'd like to hear that BigQuery talk! I missed it at HRNUG. If people are interested, I could throw together a talk on what I'm doing with Vagrant.

**Comment by rmcastil** [comment]
SOLD!

@switchspan can you go ahead and put yourself down for the May talk?
@lynnaloo do you want the vagrant talk to be a 30-45 min one or a lighting one?

**Comment by lynnaloo** [comment]
I haven't put the talk together yet, but I'm thinking about 30 minutes so that it can be interactive. I've never spoken at any of the user groups so it will be a first for me! If you can schedule me later this summer (July/August) that would work best.

**Comment by switchspan** [comment]
@rmcastil - No problem - I will put something together for the Meetup entry.
@lynnaloo - Awesome -- I will put you on the calendar. :)

**Comment by metaskills** [comment]
THANKS KEN!!!
