### ISSUE TITLE
New Shirts! How?

### ISSUE THREAD

**Issue by metaskills** [757rb/organizing#12]
I want to start planning for a re-print of our t-shirt.

https://www.booster.com/757rb

Idea would be to do same design and shirt as used in the campaign. I want to make sure of the following:
- No underbase used. This makes the ink feel coarse and thick.
- No halftones used. Previous did, and looked odd.

That said, the ideas for discussion would be:
- Would another Booster campaign work? 
- Maybe I can get CustomInk to do a few on sponsorship. That would add a CustomInk "inky" to the sleeve I think.
- Would we want to change the shirt? For example, [this purple](http://www.customink.com/designs/757rb5cm2/djn0-000x-hz6v/hotlink) is kind of cool.
- Would we want to change the design? Like add a 757rb to the sleeve?
- Would we want to theme a design? Maybe there is an event to co-brand? RailsGirls, etc?

**Comment by rmcastil** [comment]
TBH I love the test print the best. The shirt may have felt 'hard' but that blue looked pretty awesome with the logo. Plus having the 8bit 757rb on the back was pretty cool. I think the tri blend is what throws me off with the color. Or maybe go with a hoddie instead of a T?

**Comment by metaskills** [comment]
> TBH I love the test print the best.

You mean [this one](https://www.customink.com/designs/757rbf/djn0-000v-yegp/retrieve) which had to be printed on the teal since the quantity was low and the Baby Blue could not be printed with digital ink. I really dislike digital printing, feels 80's mall'ish.

**Comment by lynnaloo** [comment]
I didn't know you could do more than one Booster campaign! I like the purple, but I might have a different opinion about the pastels than many of the guys :) My only request is that we don't do our Booster campaigns at the same time (ninja cat v mermaid).

**Comment by rmcastil** [comment]
Oooh. How about doing the ninja cat first then doing a ninja cat + mermaid?

**Comment by lynnaloo** [comment]
ooooooh a Booster campaign shirt with multiple user groups on it? That could be cool.

**Comment by metaskills** [comment]
Great idea. Polyglot FTW!

**Comment by switchspan** [comment]
Not a bad idea. Although HRNUG doesn't really have a mascot (AFAIK) -- I do think there is a logo. @1kevgriff would be the one to ask on that.

**Comment by qwo** [comment]
I'm in for a couple more shirts!

Also figuring how to clone Ken's Campaign Shirt icon :) off the http://757rb.org site

**Comment by metaskills** [comment]
OK, I put in a request to CustomInk for a sponsored shirt order. Will let y'all know what happens. BTW, I have come to also love the American Apparel 50/50 and think the 757rb Booster design [looks awesome](http://www.customink.com/designs/757rb5050p/dxn0-0011-h6w0/hotlink) on the Heather Lake Blue style.

![screen shot 2014-06-08 at 5 06 29 pm](https://cloud.githubusercontent.com/assets/2381/3212292/ffc3bcd2-ef50-11e3-88b0-d0a1284aceb2.png)

**Comment by lynnaloo** [comment]
That looks great!

**Comment by switchspan** [comment]
Ditto!

On Sun, Jun 8, 2014 at 7:13 PM, Linda Nichols notifications@github.com
wrote:

> That looks great!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/757rb/organizing/issues/12#issuecomment-45451491.

## 

"You can't get unless you give. And you have to give without wanting to
get."
—Theodore H. White

**Comment by metaskills** [comment]
So I heard back from CustomInk today and they said they would fund another round of shirts. Will report back on what I am thinking about later when I setup new designs.

**Comment by switchspan** [comment]
Sweet!

On Wed, Jun 11, 2014 at 4:40 PM, Ken Collins notifications@github.com
wrote:

> So I heard back from CustomInk today and they said they would fund another
> round of shirts. Will report back on what I am thinking about later when I
> setup new designs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/757rb/organizing/issues/12#issuecomment-45796809.

## 

"You can't get unless you give. And you have to give without wanting to
get."
—Theodore H. White

**Comment by metaskills** [comment]
So the current idea I am floating is this **American Apparel Tri-Blend T-shirt - Tri-Orchid**. It comes in youth small to two extra large. 

![9d8ed570-0292-4044-971d-f0e0e0b6dfdc](https://cloud.githubusercontent.com/assets/2381/3279703/67389342-f410-11e3-9bb5-d3d7afdf4a32.png)

**Comment by lynnaloo** [comment]
I really love this one!

**Comment by metaskills** [comment]
So these shirts have been ordered. Our CustomInk sponsorship really paid off this year, total cost for this 4c front and 2c back and following quantities was close to $700. I'll pass on the appreciation when I am up there next week. ETA for delivery just might be Tuesday or Wednesday next week. 

![sizes](https://cloud.githubusercontent.com/assets/2381/3454964/0b986d9c-01d9-11e4-81bd-e0503568c688.png)

**Comment by metaskills** [comment]
Closing this issue. New shirts are in and some have already been handed out. DM me on Twitter if needed.

**Comment by metaskills** [comment]
OK, I just opened a v2 Booster for 757rb purple. The price is set so that it does not make profit if we hit the goal, or very little.

https://www.booster.com/757rb-v2

I will add this to the 757rb.org HP like the old one. I do want to point out that I have about 8 shirts leftover from the initial order, but maybe this is a good way to get a few more out there too.
