### ISSUE TITLE
2013 - Ryan's Prospects From Ruby DCamp

### ISSUE THREAD

**Issue by metaskills** [757rb/organizing#13]
- Andrew Culver @andrewculver (@rmcastil requested via twitter)
- Zander @_ZPH (@rmcastil requested via Ruby DCamp)
- Hiro Asari @hiro_asari (@rmcastil requested via Ruby DCamp)
- Jason Wieringa @jwieringa (@rmcastil requested via Ruby DCamp)
- Sean Marcia @seanmarcia (@rmcastil requested via Ruby DCamp)
- Jamie Wright @jwright (@rmcastil requested via twitter)

**Comment by seanmarcia** [comment]
Wow, what amazing company I find myself in with this list :)

**Comment by rmcastil** [comment]
@SeanMarcia the point is, come on down! We'd love to have anyone who is excited to present.

**Comment by metaskills** [comment]
LOL, It just occurred to me another great reason for this style of organization, the cc's to Github. Epic win! @SeanMarcia, yes, by all means do come down if you have the time or a topic you want to practice. I myself will be up at DCRUG #8 next month too and am looking to take more time presenting. 

I don't have a summer home to share lodging, but I'm sure anyone @757rb would love to help in anyway we could for any speaker that wants to tour our area. Cheers!

**Comment by rmcastil** [comment]
:+1:

**Comment by rmcastil** [comment]
@SeanMarcia I think you're sandbagging dude. It looks like you're [presenting](http://www.railsconf.com/program) at RailsConf :smile:

**Comment by seanmarcia** [comment]
That's just because they had a quota of Canadians to fill and no others submitted talks ;)

**Comment by jwieringa** [comment]
Yeah, it is pretty effective organization. :smile:

**Comment by metaskills** [comment]
I was talking to some people at RubyNation and flaked because we do not have @zph on the calendar for July 10th (http://www.meetup.com/757-rb/events/qrhwffyskbnb/). Can we get Zander's talk info and post it up on the meetup?

cc @rmcastil @therubyrep

**Comment by zph** [comment]
"Surviving Large Unfamiliar Codebases: A Harrowing Tale of Legacy Apps and Oracle Databases"

That's the working title :smile:.

I'll be in town all day Thursday, either co-working or working from a decent coffeeshop!

**Comment by jwieringa** [comment]
@zph That sounds... too much like real life.

**Comment by metaskills** [comment]
@zph Please text me when you are in town or nearby.
(:seven::five::seven:) :six::seven::two:-:two::two::four::six:

**Comment by zph** [comment]
@metaskills Sounds good, I'll be arriving the night before, maybe around 8 or 9pm depending on how the drive goes.

**Comment by metaskills** [comment]
@jwieringa It was good to meet you at Arlington Ruby this week.
