### ISSUE TITLE
2014-07-10 Meetup

### ISSUE THREAD

**Issue by switchspan** [757rb/organizing#14]
I am adding this as a reminder that @lynnaloo is doing the July talk on how she is using vagrant. :)

**Comment by switchspan** [comment]
Oooops...tried to label and I accidentally closed this. :-/

**Comment by lynnaloo** [comment]
Looks like you guys might be double-booked for July: https://github.com/757rb/organizing/issues/13#issuecomment-45448914. I can defer to an out-of-towner if need be.

**Comment by rmcastil** [comment]
That's my bad! I'm sorry.

Zander followed up with us recently and I didn't even bother to check the
issues. I let Mandy handle the scheduling and I'm pretty sure I never told
her to double check the issues as well.

Is your talk ready? We can move things around to make this work if so. I'd
hate it if I started preparing a talk just to find out I was accidentally
booted.

**Comment by metaskills** [comment]
My bad too, I was reacting to the email I saw to Zander and did not stop to think to double check an open issue for the same month.

**Comment by lynnaloo** [comment]
I only have a rough outline so it's totally cool to bump me to the fall when you have an opening.

**Comment by metaskills** [comment]
Ohhh... I just noticed that @switchspan has a new fancy Github avatar! Sweet.

**Comment by metaskills** [comment]
@rmcastil If the new shirts from #12 come when I expect, I'll make sure to get some to you. I want to make sure that @zph gets his too.

**Comment by zph** [comment]
Ooo, those look really nice. Thanks for including me in that @metaskills

**Comment by metaskills** [comment]
@zph What size are you? Here is the [size chart](http://www.customink.com/items/sizing/169900_lineup/standard.htm)

**Comment by zph** [comment]
@metaskills 2XL

**Comment by bambilee1116** [comment]
@lynnaloo Can you speak at next month's meetup on Thursday, August 14th?

**Comment by metaskills** [comment]
Closing this issue since it is for last month's meetup. @lynnaloo, please answer to #18 if you can.

**Comment by lynnaloo** [comment]
I can't do August, sorry :( Keep me in mind for the fall.

**Comment by rmcastil** [comment]
@metaskills we're just going to cancel the August meeting then? cc @therubyrep

**Comment by metaskills** [comment]
Ryan, I had not planned on it. My idea was to just throw something together for the out of town crew. Since I have not yet focused on the August presentation, what do you think?

**Comment by qwo** [comment]
Hey @rmcastil and @metaskills,

@xtuple is kicking off our haxTuple event: hack to meet the Woz event in August 9th\* and goes on all month.

In lieu of a traditional meetup how about a hack event? \* Maybe @norfolkjs will also be interested

http://www.xtuple.com/events/haxtuple-calling-all-developers-30-day-hacking-kick-off

More info in this wiki: https://github.com/xtuple/xtuple/wiki/haxTuple-2014

**Comment by rmcastil** [comment]
@stanzheng I like the idea of this. The summer months are usually slow and people have been asking for a hack event.

**Comment by qwo** [comment]
let us know @lynnaloo, @tjwebb and @shackbarth can help make this happen.

**Comment by tjwebb** [comment]
Yes. In addition "meet Steve Wozniak" there will be other incentives as well

**Comment by switchspan** [comment]
+1 on @rmcastil comments. I was going to suggest a hack event in the absence of a speaker. What do you think @metaskills ?

**Comment by qwo** [comment]
@switchspan @gdghr is invited too :). 

There will be beer, pizza, and prizes. what more could you want.

**Comment by lynnaloo** [comment]
The infrastructure is there to write applications in languages other than JavaScript using our REST API, but we need some good ideas and developers to write them :)

**Comment by switchspan** [comment]
Good ideas and developers? Damn...that rules me out. ;) (J/K!) 

Is the API for the ERP, CRM or all of the products?

**Comment by qwo** [comment]
Don't quote me on it, but i think its for all business objects so should be anything the xTuple Web supports. Contacts, Sales Orders, Accounting, etc.

For a taste, this is an app i threw together in an hour using our REST service in express to solve
- Forming Lunch Parties
- Requesting people move cars
- Friendly Hellos 

https://github.com/stanzheng/xTuple-Yo
