### ISSUE TITLE
National Day of Civic Hacking  (X-POST) Co-sponsorship opportunity with 757rb

### ISSUE THREAD

**Issue by qwo** [757rb/organizing#15]
Hi guys,

I help organize for the local CodeforAmerica Brigade Chapter CodeforhamptonRoads. 

I wanted to talk to you guys about National Day of Civic Hacking. NDOCH is a day established by the whitehouse open science and technology policy to encourage citizens to use public data and technology to build tools for their local neighborhoods.
http://www.whitehouse.gov/blog/2014/04/17/celebrating-second-annual-national-day-civic-hacking

We're looking to have an event Saturday May 31st at the Virginia Beach Central Library. 
We're hoping to make it a hands on and skills based learning day where participants are encouraged to try to use and learn about technology to enact change in their communities. 

We're looking for skills based mentors and possible workshop speakers to facilitate an informal type of hackathon and learning atmosphere. (examples would be: html/css/js basics, rails up and running, or intro to github) 

We're partnering with other local user groups and our tentative theme right now is Using technology to battle Climate Change. 

If anyone is interested or available in speaking/mentoring/participating feel free to msg me or sign up here. http://hrva.eventbrite.com

**Comment by metaskills** [comment]
I would love to do a CSS preprocessor intro, but have to check with the misses first. Saturday is our farmer's market day and home todo day. I will report back.

**Comment by qwo** [comment]
Awesome Thanks @metaskills! :)
