### ISSUE TITLE
2014-06-12 Meetup

### ISSUE THREAD

**Issue by metaskills** [757rb/organizing#16]
Hey everyone! I had a great time at DCRUG and got to talk with @seanmarcia about coming down and presenting his saving the planet talk for us!!!!!!

Sean, can you reply here and let us know if this date works for you. We can even change it or do the month after.

**Comment by seanmarcia** [comment]
Sorry for the slow response, I've been waiting to ensure my wife can get time off from work and it looks like she can. I'm excited to see you all soon!

Time to start finding some guidebooks for down there :)

**Comment by metaskills** [comment]
Woohoo!!! Sean, is this OK to post to the meetup page?

### Saving the World (literally) with Ruby on Rails

#### Sean Marcia

Two thirds of honeybee hives have died out in Virginia. Is it possible for us to devise a way of monitoring beehives in remote locations to find the cause? Enter a raspberry pi + rails. Using a combination of this robust hardware and software solution, we were able to successfully track, monitor and provide real time reporting on the well-being of hives from across the county. Find out how we used ruby, rails, solar panels and other libraries to provide insight into this problem.

Sean is rubyist who works at George Mason University and he has the extreme pleasure of being one of the founders/organizers of the best meetup group out there, Arlington Ruby.
- Follow [@seanmarcia](https://twitter.com/seanmarcia)

**Comment by metaskills** [comment]
cc @rmcastil @switchspan

**Comment by seanmarcia** [comment]
Looks good to me :)

**Comment by metaskills** [comment]
Done deal. http://757rb.org

**Comment by switchspan** [comment]
Sounds good to me too!

On Wed, May 14, 2014 at 5:04 PM, Ken Collins notifications@github.comwrote:

> Done deal. http://757rb.org
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/757rb/organizing/issues/16#issuecomment-43137497
> .

## 

"You can't get unless you give. And you have to give without wanting to
get."
—Theodore H. White

**Comment by rmcastil** [comment]
:+1:

**Comment by metaskills** [comment]
@SeanMarcia Please text or call me with your travel plans or needs as the date gets closer. Maybe we can hangout, etc. My cell phone number is:

( :seven: :five: :seven: ) :six: :seven: :two: - :two: :two: :four: :six:

**Comment by metaskills** [comment]
FYI, spoke to @SeanMarcia at RubyNation and we are still on track. Sean told me we will likely hear from him soon on travel details. I would love to open up my office for co-workering and grilled cheese if anyone is interested.

**Comment by metaskills** [comment]
I think @karledurante, @cmar, and/or @rmcastil can testify that I have room for up to 3 people to hang out and co-work here in my small office. Pretty cozy. Cant wait. Sean!

**Comment by rmcastil** [comment]
I can come by Thursday but can't make the talk. We've got my kids' end of the year picnic.

**Comment by metaskills** [comment]
Closing this issue out. Thanks again for coming down @SeanMarcia!!!
