### ISSUE TITLE
2014-xx-xx Jim Gay

### ISSUE THREAD

**Issue by metaskills** [757rb/organizing#18]
So I talked to @saturnflyer at RubyNation and got a personal demo of his [**Eastward Ho! A clear path with OO**](http://www.rubynation.org/schedule/index?schedule=yes#jim_gay) talk and wanted to reach out to him to see if he can do the same talk (or anything really) for our group and visit Norfolk/VaBeach. Thoughts? No rush.

**Comment by rmcastil** [comment]
I'm down for it. I'd love to have @saturnflyer down here again.

**Comment by saturnflyer** [comment]
Sounds great!

**Comment by metaskills** [comment]
Changing this topic from August meetup to future 2014 one in general. Also, I canceled the August 14th meetup in lieu of the one we had last week and cross promotion with #21

**Comment by metaskills** [comment]
@saturnflyer I'm still game for doing an Arlington Ruby presentation. Thoughts?

**Comment by saturnflyer** [comment]
:cry:

**Comment by metaskills** [comment]
@saturnflyer Wait, were you coming down? Cause if so, that would be awesome and I would need to post details!!!

**Comment by rmcastil** [comment]
@saturnflyer @metaskills did you guys ever resolve this?!

**Comment by saturnflyer** [comment]
Sorry guys. I was mostly computer-less this weekend. 
I'm still game for doing this but can reschedule to another date without a problem.

@metaskills we're in the midst of a potential venue change for Arlington Ruby so our schedule might be up in the air. i'll keep you posted

**Comment by metaskills** [comment]
@saturnflyer - I would like to reschedule to next month, September 11th, or any day next month that lines up with your schedule. The way I see it, your talk is so incredible cool and we did not do right by you getting this up on the meetup site which would have allowed us to communicate better that you were coming down and promote the talk. That was my bad! So Sorry!

If you are cool with September, ping me and let me know. If not, we can re-open the 14th (this Thursday) too. Either way, I need short description of that talk. Guess I could have gotten it from RubyNation too?

**Comment by metaskills** [comment]
@saturnflyer can we pencil you in?

**Comment by saturnflyer** [comment]
yes! game on.

Sorry for the delayed reply

On Thu, Aug 21, 2014 at 12:42 PM, Ken Collins notifications@github.com
wrote:

> @saturnflyer https://github.com/saturnflyer can we pencil you in?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/757rb/organizing/issues/18#issuecomment-52947243.

## 

Write intention revealing code #=> http://www.clean-ruby.com

Jim Gay
Saturn Flyer LLC
571-403-0338

**Comment by metaskills** [comment]
Jim, can I use this description from Ruby Nation for the talk?
http://www.rubynation.org/schedule/index?schedule=yes#jim_gay

**Comment by metaskills** [comment]
To late! I already did. Let me know if this is good for you.
http://757rb.org
