### ISSUE TITLE
2014-12-?? TravisCI / Hiro Asari

### ISSUE THREAD

**Issue by qwo** [757rb/organizing#19]
@rmcastil was trying to get Hiro from TravisCI to come up to Norfolk. We already have him coming to speak in December for @norfolkjs

https://github.com/norfolkjs/logistics/issues/39

He suggested a joint event and combine forces! We have xTuple as a location and beer sponsor so far so more sponsors for food or other swags appreciated!

maybe could be a 757polyglot event @1kevgriff

Thoughts Appreciated!

**Comment by metaskills** [comment]
I am a total fan of this idea! Would love to do a joint meetup with @BanzaiMan.

**Comment by lynnaloo** [comment]
This is starting to sounds like the 757 Dev CHRISTMAS PARTY. Egg Nog sponsor??

**Comment by metaskills** [comment]
I'm more interested in the Whiskey Sponsor™ to go with the egg nog.

**Comment by metaskills** [comment]
Changed topic to "2014-12-?? TravisCI / Hiro Asari"

**Comment by qwo** [comment]
Hi Ken, so we typically do the third monday of every month. So if Linda checks my calendar math its 

December 15th, 2014. This should match up with whats planned in the @norfolkjs issue tracker

**Comment by lynnaloo** [comment]
I had already scheduled Hiro for Norfolk.js's December 15th meeting at xTuple before I knew he did Ruby or knew @rmcastil. It just came up by coincidence at the last Ruby meeting.

I originally contacted him early this fall but his schedule didn't permit. His Travis-CI talk would work for a cross-language meetup. 

https://github.com/norfolkjs/logistics/issues/39

**Comment by qwo** [comment]
i already fired the @1kevgriff batsignal but he hasn't arrived. Dunno if hes back from CodeStock yet.

**Comment by BanzaiMan** [comment]
I am only 3 hours away, and the meeting would be far enough in advance; so I can be pretty flexible on the date.

**Comment by lynnaloo** [comment]
Since I already have the location set, I'd like to stick to December 15th.

**Comment by rmcastil** [comment]
Yeah December is usually unpredictable. If we can have an out of town
speaker, end of the year speaker, plus joint meetup I think the turnout
will be great.

**Comment by 1kevgriff** [comment]
Everyone on this thread minus @rmcastil (not a member) and @BanzaiMan are organizers on the polyglot group.  If you all wanna schedule something under the polyglot group - feel free (http://www.meetup.com/757-Polyglot-Developers/).  Don't lemme hold you all up if you wanna use it.

**Comment by metaskills** [comment]
Thanks Kevin!

**Comment by metaskills** [comment]
Thanks from this end too @BanzaiMan I just got a fresh batch of 757rb stickers and I am going to send a few dozen your way.
