### ISSUE TITLE
Open Thread On How To Use This Repo

### ISSUE THREAD

**Issue by metaskills** [757rb/organizing#2]
### Files/Folders
- Do we keep everything in one big README.md or make folders?
- If folders, should we use ISO8601 date format? For example `events/2013-12-14-coderetreat.md` is a neat folder/file idea?
### Misc.
- Always use upper case and periods. This is not code comments.
- Always try to link things. For instance, twitter handles, etc.

**Comment by switchspan** [comment]
I like all of your ideas on **Files/Folders** and **Misc.**, so I second the above suggestions.
A couple of additional suggestions:

#### Files/Folders
- For folders like events, if we use the ISO8601 format, we archive them yearly into a subfolder with the year. For example `events/2012/2012-12-08-coderetreat.md`. This will make a nice archive for reference later.

**Comment by metaskills** [comment]
cc @rmcastil @itsEconomics

Gonna close this issue. I have really enjoyed the way @NorfolkJS has used github issues for topics. Check it out there and look at how they use labels. Seems pretty cool and way more easy to include everyone on the conversation because we should all be "watching" this repo right?

https://github.com/norfolkjs/logistics/issues?labels=&page=1&state=open

**Comment by rmcastil** [comment]
@metaskills :+1:

**Comment by itsEconomics** [comment]
Watching :)

Ian
Personal website: www.itseconomics.com
