### ISSUE TITLE
Speaker for October

### ISSUE THREAD

**Issue by rmcastil** [757rb/organizing#22]
Do we have one? @lynnaloo did you want to give your presentation?

**Comment by lynnaloo** [comment]
I still want to give it, but I'm too booked in October with xTupleCon and my kids class :/

**Comment by lynnaloo** [comment]
If you want to put me down for November, though, I'm down!

**Comment by rmcastil** [comment]
@metaskills any ideas?!

**Comment by metaskills** [comment]
Oh... for the meeting just about to happen? No. Wanna tap dance? Ryan, I can make something up and talk, maybe you would be interested too? Hack night?

**Comment by rmcastil** [comment]
I could do something like "Welcome to my nightmare: Building 90% of an web
app with ActiveAdmin" but I'm just spitballing here.

**Comment by metaskills** [comment]
Whoa... I would love to hear that!

**Comment by rmcastil** [comment]
The other possibility is to have @mbuckbee speak about how he's built a heroku add-on and generated several thousand in monthly recurring revenue.

**Comment by itsEconomics** [comment]
Do any of you know how to create webhooks within a rails application?

**Comment by itsEconomics** [comment]
Because I'd love for someone to speak on that ;)

**Comment by metaskills** [comment]
No... no web hook experience. Done pusher before. I want to hear Ryan's active admin. I've always nah sayed using tools like that and I want to check my gut on how I feel about those projects. Seems like a winner?

**Comment by rmcastil** [comment]
I'll prepare one for next time. I might have gotten Buckbee to speak about
his heroku experience.

**Comment by rmcastil** [comment]
Just announced the meeting: http://www.meetup.com/757-rb/events/208313112/

**Comment by metaskills** [comment]
Thanks Ryan and Michael!

**Comment by switchspan** [comment]
+1 on webhooks. I would def. like to hear about making a Heroku add-on.
