### ISSUE TITLE
2015-03-12 Christopher Sexton & Beacon Tech 🚨

### ISSUE THREAD

**Issue by metaskills** [757rb/organizing#23]
So @csexton did a talk at RubyConf title [BLE Beacons & Ruby](http://rubyconf.org/program#prop_610) and I though tit would be really cool to have him down in this area to talk about that or maybe anything else Ruby or hardware related to the company he works for http://www.radiusnetworks.com

**Comment by metaskills** [comment]
cc @lynnaloo

**Comment by csexton** [comment]
Sounds rad! I've been meaning to come visit for a while and this is a great reason for me to get my act together. I'd be happy to do (an updated version) of my "[Dramatic Intro Music: Bluetooth Low Energy Beacons and Ruby](https://gist.github.com/csexton/9cf57eb2b95966c1916e)" talk, or can do something more hands on with the Radius Networks hardware. 

Is the venue well suited to a workshop, presentation, or something entirely different?

**Comment by metaskills** [comment]
Yes, lets do it. How do you feel about any of the following dates?
- Thu Mar 12
- Thu Apr 9
- Thu May 14

As is now the venue is 757creativespace and is more work/presentation. There is a big round table conference area.

**Comment by csexton** [comment]
The kids said I can go but only if I can get them some of the "jewel mermaid" stickers.

Can I take the March 12th date?

**Comment by metaskills** [comment]
You can, I just posted all the details. I will STICKERS! You bring the coolness :)

http://www.meetup.com/757-rb/events/219887528/

I'll touch base before hand and coordinate travel plans with ya. Thanks again! I'll ping you back on the talks I was thinking of doing up there soon. My calendar is opening up.

**Comment by metaskills** [comment]
Hey Chris, the meetup seems to be shaping up. Cant wait. Can you shoot me your travel plans? What time do you plan to be in Norfolk and leaving? Also, I am headed to the new Slover Library today to see if we can get a change of venue too to accommodate the expected size. Cheers!

FYI, my cell is ( :seven: :five: :seven: ) :six: :seven: :two: - :two: :two: :four: :six:

**Comment by csexton** [comment]
![excite](http://i.imgur.com/dnBMenZ.gif)

**I am excite!**

I was going to drive down tomorrow after traffic dies down. Then just find some place to work -- any recommendations?

**Comment by itsEconomics** [comment]
If you guys would like to work at our local maker space (http://www.757makerspace.com/ http://www.757makerspace.com/), I have access and we can all hang out there until the meeting.  Just let me know what time you want to show up and I’ll be there to let us in.

Ian

**Comment by metaskills** [comment]
Ian! Thanks. I like that idea so we can go to Handsome Biscuit for lunch too! @csexton, they close at 2pm. Can you be here before then? You wont regret it!!!

**Comment by itsEconomics** [comment]
Oh heck yea! We can even walk there from the space.

**Comment by csexton** [comment]
I have to get some stuff setup at the office in the morning, so will leave as soon as I can. 2 will be tight, but maybe I95 will be kind.

**Comment by metaskills** [comment]
@csexton That'll be OK. I will work something out for ya. BTW, can you text me when you are on the Road so we can ping each other as you get close. My number is above.

**Comment by csexton** [comment]
Will do.

**Comment by metaskills** [comment]
Thanks @csexton! It was great visiting Arlington Ruby too.
