### ISSUE TITLE
2014-04-08 - CVREG - Metaprogramming Sass

### ISSUE THREAD

**Issue by metaskills** [757rb/organizing#5]
I have agreed to give this talk to the CVREG group. I need to finish my talk notes and send it to them. Once I do, I need to email it to the following people.

Chris Allport allportdc@yahoo.com
Jeremy jeremy6d@gmail.com

**Comment by rmcastil** [comment]
@metaskills did you want to practice giving it at our April meeting?

**Comment by metaskills** [comment]
Proposed CVREG date is April 8th.

**Comment by metaskills** [comment]
@rmcastil Yea... I think that sounds good. I talked to DCRUG and they also meet on April 10th. So I have asked them to let me present on May 8th. So I can do it for 757rb on April 10th.

**Comment by rmcastil** [comment]
@metaskills word. So you'll update meetup with your title and abstract?

**Comment by metaskills** [comment]
This went great. However, I need to totally adjust the talk to again. 

https://gist.github.com/metaskills/10083010
https://speakerdeck.com/metaskills/metaprogramming-sass

**Comment by metaskills** [comment]
From @chrisallport

> I just wanted to say thanks for presenting at CVREG this week.  I thought you did a great job.  It is pretty cool what you were able to do with Sass, some of it didn't sink in with me until I was driving home. Also, thanks for the shirt.  That is the most comfortable shirt I've ever had on the first wear. Let's keep in touch to share ideas for our groups.

I talked to Chris about Gustin & general ideas about a regional conference. Also mentioned this to @1kevgriff. Either way, totally love CVREG. PS, we need to get more shirts.

**Comment by rmcastil** [comment]
@metaskills since you're doing a world tour :+1:? Did you want to do this at 757rb in June? cc @therubyrep

**Comment by metaskills** [comment]
I do!

**Comment by metaskills** [comment]
Ryan, I do, but I wanted it to line up with #6. I am talking to Alex Proaps and Bianca Chesimard now about doing it for a cross team event. Likely with Grow, and the local UX people.
