### ISSUE TITLE
2014-xx-xx - Grow, AIGA, Etc - Metaprogramming Sass

### ISSUE THREAD

**Issue by metaskills** [757rb/organizing#6]
No date has been set, but I have started a conversation with Matt Paddock mpaddock@thisisgrow.com at Grow Interactive and they would love to host this. When I finish the work in #5 to submit to CVREG, I will followup with Matt. 

I would love some ideas on how to get more local groups to attend this talk.

**Comment by rmcastil** [comment]
when I did the coderetreat last year I just contacted all the local group organizers and asked them to throw it in their newsletter. Part of the key I see with attracting more people is the title and abstract. To a lot of Rubyists Metaprogramming Sass makes sense but that'll likely turn off potential attendees if they have no idea what those two words mean.

**Comment by lynnaloo** [comment]
I agree with @rmcastil. Even those using LESS would get a lot out of your talk as well, but might not realize it based on the title.

**Comment by metaskills** [comment]
Great advice! So in #5, it seems we may target the local talk for April 5th.

**Comment by metaskills** [comment]
I'm still gonna do this, but want to finish my thesassway.com article first.
