### ISSUE TITLE
2014-05-08 - DCRUG - Metaprogramming Sass

### ISSUE THREAD

**Issue by metaskills** [757rb/organizing#8]
David Naffis @naffis has confirmed my talk for this date. Once I finish my refactor of the talk, send him a new abstract at davidnaffis@gmail.com.

**Comment by metaskills** [comment]
Talk went well for CVREG. I am all scheduled for DCRUG.
http://www.meetup.com/dcruby/events/125375412/

Will be working on retooling the talk.

**Comment by rmcastil** [comment]
@metaskills great job bro!

**Comment by metaskills** [comment]
Thanks man, really considering we need some shirts to give away too while up there or just in general.

**Comment by metaskills** [comment]
This went really really well. Gonna post 
![friday-hug](https://cloud.githubusercontent.com/assets/2381/2928296/f462a2a6-d77a-11e3-8cfb-55ebabe95dc7.jpg) for @tenderlove on Twitter. Here is my updated speaker deck slides that I'll post to the DCRUG group. https://speakerdeck.com/metaskills/metaprogramming-sass
